QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_ST7789_SPI_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += st7789_spi

SRC += Mario_240x240.qgf.c
SRC += Black_Copper_240x240.qgf.c
SRC += test_gif.qgf.c

BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = pwm
